"use strict";
const API="/api",mode=document.body.dataset.authMode,form=document.querySelector("#auth-form"),submit=document.querySelector("#auth-submit"),alertBox=document.querySelector("#form-alert");
function redirectFor(role){location.replace(role==="admin"?"/admin.html":role==="support_agent"?"/agent.html":"/")}
async function request(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(body?.error?.message||"Something went wrong.");error.body=body;throw error}return body}
function showAlert(message,success=false){alertBox.textContent=message;alertBox.className=`form-alert${success?" success":""}`;alertBox.hidden=false}
function clearErrors(){alertBox.hidden=true;document.querySelectorAll(".field-error").forEach(x=>x.textContent="");document.querySelectorAll("input").forEach(x=>x.classList.remove("invalid"))}
function error(name,message){const target=document.querySelector(`[data-error="${name}"]`),input=document.querySelector(`[name="${name}"]`);if(target)target.textContent=message;if(input)input.classList.add("invalid")}
function validate(data){let ok=true;if(mode==="signup"&&data.full_name.trim().length<2){error("full_name","Enter your full name.");ok=false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)){error("email","Enter a valid email address.");ok=false}if(!data.password){error("password","Enter your password.");ok=false}if(mode==="signup"){if(data.password.length<12||!/[A-Z]/.test(data.password)||!/[a-z]/.test(data.password)||!/\d/.test(data.password)){error("password","Use 12+ characters with uppercase, lowercase, and a number.");ok=false}if(data.password!==data.confirm_password){error("confirm_password","Passwords do not match.");ok=false}}return ok}
document.querySelectorAll("[data-reveal]").forEach(button=>button.addEventListener("click",()=>{const input=document.querySelector(`#${button.dataset.reveal}`),show=input.type==="password";input.type=show?"text":"password";button.textContent=show?"Hide":"Show"}));
form.addEventListener("submit",async event=>{event.preventDefault();clearErrors();const data=Object.fromEntries(new FormData(form));data.email=(data.email||"").trim().toLowerCase();if(!validate(data))return;submit.disabled=true;const original=submit.firstChild.textContent;submit.firstChild.textContent=mode==="signup"?"Creating account… ":"Signing in… ";try{if(mode==="signup"){await request("/auth/signup",{method:"POST",body:JSON.stringify(data)});location.replace("/login.html?registered=1")}else{const user=await request("/auth/login",{method:"POST",body:JSON.stringify(data)});redirectFor(user.role)}}catch(err){const details=err.body?.error?.details||[];details.forEach(item=>error(String(item.field).split(".").pop(),item.message));showAlert(err.message)}finally{submit.disabled=false;submit.firstChild.textContent=original}});
(async()=>{if(mode==="login"&&new URLSearchParams(location.search).has("registered"))showAlert("Account created successfully. Sign in to continue.",true);try{const user=await request("/auth/me");redirectFor(user.role)}catch{}})();
