"use strict";
const API="/api",portal=document.body.dataset.portal,state={user:null,tickets:[],users:[],selected:null};
const $=s=>document.querySelector(s), list=$("#ticket-list"),detail=$("#detail"),metrics=$("#metrics"),toastEl=$("#toast");
async function api(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||`Request failed (${r.status})`);return b}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n}
function notify(message,error=false){toastEl.textContent=message;toastEl.className=`toast${error?" error":""}`;toastEl.hidden=false;setTimeout(()=>toastEl.hidden=true,4000)}
function pill(value){return el("span",`pill ${value||""}`,String(value||"unclassified").replace("_"," "))}
function renderMetrics(data){metrics.replaceChildren();const values=portal==="admin"?[["Total users",data.users],["All tickets",data.tickets],["Completed",data.tickets_by_status?.complete||0],["Failed",data.tickets_by_status?.failed||0]]:[["Assigned",state.tickets.length],["Pending",state.tickets.filter(x=>x.status==="pending").length],["Processing",state.tickets.filter(x=>x.status==="processing").length],["Complete",state.tickets.filter(x=>x.status==="complete").length]];values.forEach(([label,value])=>{const box=el("div","metric");box.append(el("span","",label),el("b","",value));metrics.append(box)})}
function renderTickets(){const q=$("#search").value.toLowerCase(),items=state.tickets.filter(t=>`${t.title} ${t.description} ${t.category||""}`.toLowerCase().includes(q));list.replaceChildren();if(!items.length){list.append(el("div","empty","No matching tickets."));return}items.forEach(t=>{const row=el("button",`ticket${state.selected?.id===t.id?" selected":""}`);row.append(el("strong","",t.title),el("p","",t.description));const meta=el("div","meta");meta.append(pill(t.status),pill(t.urgency),pill(t.category));row.append(meta);row.onclick=()=>{state.selected=t;renderTickets();renderDetail()};list.append(row)})}
function field(label,value){const d=el("div");d.append(el("span","",label),el("b","",value??"—"));return d}
function labeled(label,control){const wrap=el("label");wrap.append(document.createTextNode(label),control);return wrap}
function renderDetail(){const t=state.selected;if(!t){detail.replaceChildren(el("div","empty","Select a ticket to review it."));return}const body=el("div","detail-body");body.append(el("h2","",t.title),el("p","description",t.description));const grid=el("div","detail-grid");grid.append(field("Status",t.status),field("Urgency",t.urgency),field("Category",t.category),field("Queue",t.assigned_queue),field("Confidence",t.confidence==null?null:`${Math.round(t.confidence*100)}%`),field("Model",t.llm_model));body.append(grid);const actions=el("div","actions");
if(portal==="agent"){const status=document.createElement("select");["pending","processing","complete","failed"].forEach(v=>status.add(new Option(v,v,v===t.status,v===t.status)));const saveStatus=el("button","secondary","Update ticket status");saveStatus.onclick=()=>update(`/tickets/${t.id}/status`,{status:status.value});actions.append(labeled("Workflow status",status),saveStatus);const urgency=document.createElement("select");["low","medium","high","critical"].forEach(v=>urgency.add(new Option(v,v,v===t.urgency,v===t.urgency)));const category=document.createElement("select");["billing","technical","bug","account","general"].forEach(v=>category.add(new Option(v,v,v===t.category,v===t.category)));const confidence=document.createElement("input");confidence.type="number";confidence.min="0";confidence.max="1";confidence.step=".01";confidence.value=t.confidence??.8;const reasoning=document.createElement("textarea");reasoning.placeholder="Explain why the AI classification should change";const correct=el("button","","Submit classification correction");correct.onclick=()=>{if(!reasoning.value.trim())return notify("Correction reasoning is required.",true);update(`/tickets/${t.id}/classification`,{urgency:urgency.value,category:category.value,confidence:Number(confidence.value),reasoning:reasoning.value.trim()})};actions.append(labeled("Correct urgency",urgency),labeled("Correct category",category),labeled("Confidence",confidence),labeled("Correction reasoning",reasoning),correct)}
if(portal==="admin"){const agents=state.users.filter(u=>u.role==="support_agent"&&u.is_active),select=document.createElement("select");select.add(new Option("Select support agent",""));agents.forEach(u=>select.add(new Option(`${u.full_name} (${u.email})`,u.id,u.id===t.assigned_agent_id,u.id===t.assigned_agent_id)));const assign=el("button","","Assign support agent");assign.onclick=()=>{if(!select.value)return notify("Select an active support agent.",true);update(`/tickets/${t.id}/assign`,{assigned_agent_id:select.value})};actions.append(labeled("Assigned support agent",select),assign)}body.append(actions);detail.replaceChildren(body)}
async function update(path,payload){const buttons=[...detail.querySelectorAll("button")];buttons.forEach(button=>button.disabled=true);try{const ticket=await api(path,{method:"PATCH",body:JSON.stringify(payload)}),i=state.tickets.findIndex(x=>x.id===ticket.id);if(i>=0)state.tickets[i]=ticket;state.selected=ticket;renderTickets();renderDetail();notify("Ticket updated successfully.")}catch(e){buttons.forEach(button=>button.disabled=false);notify(e.message,true)}}
function renderUsers(){const target=$("#user-list");if(!target)return;target.replaceChildren();state.users.forEach(u=>{const row=el("div","user-row"),identity=el("div");identity.append(el("b","",u.full_name),el("small","",u.email));const id=el("small","",u.id);const role=document.createElement("select");[["Customer","customer"],["Support Agent","support_agent"],["Admin","admin"]].forEach(([l,v])=>role.add(new Option(l,v,v===u.role,v===u.role)));role.onchange=async()=>{try{const changed=await api(`/admin/users/${u.id}/role`,{method:"PATCH",body:JSON.stringify({role:role.value})});Object.assign(u,changed);notify("User role updated.")}catch(e){role.value=u.role;notify(e.message,true)}};const active=el("button","",u.is_active?"Active":"Inactive");active.onclick=async()=>{try{const changed=await api(`/admin/users/${u.id}/active`,{method:"PATCH",body:JSON.stringify({is_active:!u.is_active})});Object.assign(u,changed);renderUsers();notify("User access updated.")}catch(e){notify(e.message,true)}};row.append(identity,id,role,active);target.append(row)})}
async function load(){try{state.user=await api("/auth/me");if((portal==="admin"&&state.user.role!=="admin")||(portal==="agent"&&state.user.role!=="support_agent"))return location.replace(state.user.role==="customer"?"/":"/login.html");$("#current-user").textContent=state.user.full_name;if(portal==="admin"){const [analytics,users,tickets]=await Promise.all([api("/admin/analytics"),api("/admin/users"),api("/tickets?limit=100&offset=0")]);state.users=users;state.tickets=tickets.items;renderMetrics(analytics);renderUsers()}else{const tickets=await api("/tickets?limit=100&offset=0");state.tickets=tickets.items;renderMetrics()}renderTickets();renderDetail()}catch(e){if(e.message.includes("Authentication"))location.replace("/login.html");else notify(e.message,true)}}
$("#search").addEventListener("input",renderTickets);$("#refresh").onclick=load;$("#logout").onclick=async()=>{await api("/auth/logout",{method:"POST"}).catch(()=>{});location.replace("/login.html")};document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#tickets-tab").hidden=b.dataset.tab!=="tickets";$("#users-tab").hidden=b.dataset.tab!=="users"});load();
